package com.tanghulu.launcher.core

import com.tanghulu.launcher.util.HttpUtil
import com.tanghulu.launcher.util.Json
import java.io.IOException
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.util.LinkedHashMap

/**
 * Version manifest management: fetches the Mojang version manifest and scans locally installed versions.
 */
class VersionManager {

    /** Fetch the version manifest (as a Map); throws IOException on failure. */
    @Throws(IOException::class)
    fun fetchManifest(source: DownloadSource): Map<String, Any?> {
        val text = HttpUtil.getText(source.manifestUrl())
        return Json.asObject(Json.parse(text)) ?: throw IOException("Invalid version manifest")
    }

    /** Find the URL of a version entry in the manifest. */
    fun findVersionUrl(manifest: Map<String, Any?>, id: String): String? {
        val versions = Json.asArray(manifest["versions"])
        if (versions != null) {
            for (v in versions) {
                val entry = Json.asObject(v)
                if (entry != null && id == Json.optString(entry, "id")) {
                    return Json.optString(entry, "url")
                }
            }
        }
        return null
    }

    /** Scan installed version ids under the game directory. */
    fun getLocalVersions(gameDir: Path): List<String> {
        val versionsDir = gameDir.resolve("versions")
        if (!Files.isDirectory(versionsDir)) return emptyList()
        val result = ArrayList<String>()
        try {
            Files.list(versionsDir).use { dirs ->
                dirs.filter { Files.isDirectory(it) }.forEach { d ->
                    val id = d.fileName.toString()
                    if (Files.isRegularFile(d.resolve("$id.json"))) result.add(id)
                }
            }
        } catch (e: IOException) {
            // Ignore read failures
        }
        result.sort()
        return result
    }

    /**
     * Delete a locally installed version (removes the entire {@code versions/<id>} directory).
     * Performs path validation to avoid directory traversal; returns false when the directory does not exist.
     */
    fun deleteVersion(gameDir: Path, id: String): Boolean {
        if (id.isBlank() || id.contains("..") || id.contains('/') || id.contains('\\')) return false
        val base = gameDir.resolve("versions").normalize()
        val dir = base.resolve(id).normalize()
        if (!dir.startsWith(base) || !Files.isDirectory(dir)) return false
        return try {
            Files.walk(dir).use { paths ->
                paths.sorted(java.util.Comparator.reverseOrder()).forEach { Files.deleteIfExists(it) }
            }
            true
        } catch (e: IOException) {
            false
        }
    }

    /** Local file of the version JSON. */
    fun localVersionJson(gameDir: Path, id: String): Path =
        gameDir.resolve("versions").resolve(id).resolve("$id.json")

    /** Local file of the version jar. */
    fun localVersionJar(gameDir: Path, id: String): Path =
        gameDir.resolve("versions").resolve(id).resolve("$id.jar")

    /**
     * Resolve the version JSON: prefer reading the local file, otherwise fetch from the network and save locally.
     * Returns the parsed root object (Map).
     */
    @Throws(IOException::class)
    fun loadOrDownloadVersionJson(
        gameDir: Path, id: String, source: DownloadSource, manifestVersionUrl: String?
    ): Map<String, Any?> {
        val local = localVersionJson(gameDir, id)
        if (Files.isRegularFile(local)) {
            val root = Json.asObject(Json.parse(Files.readString(local, StandardCharsets.UTF_8)))
            if (root != null) return root
        }
        // Download: look up from the version manifest first when no URL is provided
        var url = manifestVersionUrl
        if (url.isNullOrEmpty()) {
            url = findVersionUrl(fetchManifest(source), id)
        }
        url = source.versionJson(url)
        if (url.isNullOrEmpty()) throw IOException("No download URL for version $id")
        val text = HttpUtil.getText(url)
        val root = Json.asObject(Json.parse(text))
            ?: throw IOException("Invalid version JSON for $id")
        Files.createDirectories(local.parent)
        Files.writeString(local, text, StandardCharsets.UTF_8)
        return root
    }

    /** Version info after merging the inheritance chain. */
    class ResolvedVersion(
        /** The merged, complete version JSON. */
        @JvmField val json: Map<String, Any?>,
        /** The version id that actually provides the client jar (possibly a parent in the inheritance chain). */
        @JvmField val jarId: String
    )

    /**
     * Parse the version JSON and merge the {@code inheritsFrom} inheritance chain (see HMCL's GameInstancePatch).
     * Version JSONs generated by mod loaders (Fabric/Forge, etc.) are attached to vanilla via {@code inheritsFrom};
     * this recursively merges the parent's libraries / arguments / download info.
     *
     * @return the merged, complete JSON plus the version id that actually provides the client jar
     */
    @Throws(IOException::class)
    fun resolve(gameDir: Path, id: String, source: DownloadSource): ResolvedVersion {
        val json = loadOrDownloadVersionJson(gameDir, id, source, null)
        return resolveFrom(gameDir, id, json, source)
    }

    @Throws(IOException::class)
    private fun resolveFrom(
        gameDir: Path, id: String, json: Map<String, Any?>, source: DownloadSource
    ): ResolvedVersion {
        val inheritsFrom = Json.optString(json, "inheritsFrom")
        if (inheritsFrom.isNullOrEmpty()) return ResolvedVersion(json, id)
        // Whether the child version bundles its own client jar (decides whether the client jar comes from itself or the parent)
        val downloads = Json.asObject(Json.opt(json, "downloads"))
        val hasClient = downloads != null && Json.asObject(downloads["client"]) != null
        val parent = resolve(gameDir, inheritsFrom, source)
        return ResolvedVersion(mergeVersion(json, parent.json), if (hasClient) id else parent.jarId)
    }

    /** Merge child/parent version JSONs: child fields win; libraries are deduplicated by name (child overrides parent). */
    private fun mergeVersion(child: Map<String, Any?>, parent: Map<String, Any?>): Map<String, Any?> {
        val merged = LinkedHashMap<String, Any?>(parent)
        for ((k, v) in child) {
            if (k == "libraries") {
                merged["libraries"] = mergeLibraries(child, parent)
            } else {
                merged[k] = v
            }
        }
        return merged
    }

    private fun mergeLibraries(child: Map<String, Any?>, parent: Map<String, Any?>): List<Any?> {
        val byName = LinkedHashMap<String, Any?>()
        appendLibraries(byName, Json.asArray(parent["libraries"]))
        appendLibraries(byName, Json.asArray(child["libraries"]))
        return ArrayList(byName.values)
    }

    private fun appendLibraries(byName: LinkedHashMap<String, Any?>, libraries: List<Any?>?) {
        if (libraries == null) return
        for (o in libraries) {
            val lib = Json.asObject(o)
            if (lib != null) {
                val name = Json.optString(lib, "name")
                if (name != null) byName[name] = lib // Later writes override, i.e. the child version wins
            }
        }
    }

    /** Get display data from the version manifest: id + type (release/snapshot/old_*). */
    fun listManifestEntries(manifest: Map<String, Any?>): Map<String, String> {
        val result = LinkedHashMap<String, String>()
        val versions = Json.asArray(manifest["versions"])
        if (versions != null) {
            for (v in versions) {
                val entry = Json.asObject(v)
                if (entry != null) {
                    val id = Json.optString(entry, "id")
                    val type = Json.optString(entry, "type", "release") ?: "release"
                    if (id != null) result.putIfAbsent(id, type)
                }
            }
        }
        return result
    }

    /** A single entry of the version manifest, used for list display. */
    class ManifestEntry(
        @JvmField val id: String,
        @JvmField val type: String,
        /** Original release time (ISO-8601, may be null). */
        @JvmField val releaseTime: String?
    )

    /** Get display data from the version manifest (id + type + release time), preserving the original order in the manifest. */
    fun listManifestVersions(manifest: Map<String, Any?>): List<ManifestEntry> {
        val result = ArrayList<ManifestEntry>()
        val versions = Json.asArray(manifest["versions"])
        if (versions != null) {
            for (v in versions) {
                val entry = Json.asObject(v) ?: continue
                val id = Json.optString(entry, "id")
                if (id != null) {
                    result.add(
                        ManifestEntry(
                            id,
                            Json.optString(entry, "type", "release") ?: "release",
                            Json.optString(entry, "releaseTime")
                        )
                    )
                }
            }
        }
        return result
    }
}
